### ISSUE TITLE
(No rush) Remove personal information

### ISSUE THREAD

**Issue by jesusmah** [ibm-cloud-architecture/refarch-cloudnative-wfd#3]
I'd suggest to anonymise information in our repos. This mainly applies to the output snippets we show in our READMEs for user guidance. For instance, I could read Hema's email in the following readme:

https://github.com/ibm-cloud-architecture/refarch-cloudnative-wfd/blob/microprofile/minikube_readme.md#setting-up-your-environment

More precisely, on a code block in that section you output:

$HELM_HOME has been configured at /Users/**Hemankita.Perabathini@ibm.com**/.helm.

In my READMEs, whatever makes reference to me (either an email or a path/folder) I just simply change it to user. For instance:

almarazj@ie.ibm.com --> user@ibm.com
/home/users/jesusalmaraz/workspace --> /home/users/user/workspace.

**Comment by Hemankita** [comment]
Removed personal info
